package co.gov.coljuegos.siicol.ejb.enumeration;


/**
 * Enumerado para los Conceptos de Cuota.
 * - Obtenido de la tabla <i>SII_CONCEPTO_CUOTA</i>.
 */
public enum EnumConceptoCuota {
    
    DERECHOS_DE_EXPLOTACION(1L),
    GASTOS_DE_ADMINISTRACION(2L),
    MULTA_POR_INCUMPLIMIENTO_CONTRACTUAL(3L),
    ACUERDOS_DE_PAGO_DERECHOS_DE_EXPLOTACION(4L),
    SANCION_DE_AFORO_POR_OPERACION_ILEGAL(5L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_DERECHOS_DE_EXPLOTACION(6L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_SOBRE_DERECHOS_DE_EXPLOTACION(7L),
    ACUERDOS_DE_PAGO_INTERESES_DE_MORA_POR_PAGO_EXTEMPORANEO_DERECHOS_DE_EXPLOTACION(8L),
    ACUERDOS_DE_PAGO_GASTOS_DE_ADMINISTRACION(9L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_GASTOS_DE_ADMINISTRACION(10L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_SOBRE_GASTOS_DE_ADMINISTRACION(11L),
    ACUERDOS_DE_PAGO_INTERESES_DE_MORA_POR_PAGO_EXTEMPORANEO_GASTOS_DE_ADMINISTRACION(12L),
    LIQUIDACION_DE_AFORO_DE_DERECHOS_DE_EXPLOTACION_DE_OPERACION_ILEGAL(13L),
    LIQUIDACION_DE_AFORO_DE_GASTOS_DE_ADMINISTRACION_POR_OPERACION_ILEGAL(14L),
    CLAUSULA_PENAL(15L),
    COSTAS_PROCESALES(16L),
    GASTOS_DEL_PROCESO(17L),
    DE_MISMA_VIGENCIA(18L),
    GA_MISMA_VIGENCIA(19L),
    ACUERDOS_DE_PAGO_SANCIONES(20L),
    ACUERDOS_DE_PAGO_INTERESES_DE_MORA_POR_PAGO_EXTEMPORANEO_SANCIONES(21L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_SANCIONES(22L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_SANCIONES(23L),
    ACUERDOS_DE_PAGO_MULTAS(24L),
    ACUERDOS_DE_PAGO_INTERESES_DE_MORA_POR_PAGO_EXTEMPORANEO_MULTAS(25L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_MULTAS(26L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_MULTAS(27L),
    ACUERDOS_DE_PAGO_CADUCIDAD_CLAUSULA_PENAL(28L),
    ACUERDOS_DE_PAGO_INTERESES_DE_MORA_POR_PAGO_CLAUSULA_PENAL(29L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_CLAUSULA_PENAL(30L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_CLAUSULA_PENAL(31L),
    AMPLIACION_TEMPORAL_DERECHOS_DE_EXPLOTACION(32L),
    AMPLIACION_TEMPORAL_GASTOS_DE_ADMINISTRACION(33L),
    LIQUIDACION_DE_REVISION_POR_OMISION_DE_DERECHOS_DE_EXPLOTACION(34L),
    LIQUIDACION_DE_REVISION_POR_OMISION_DE_GASTOS_DE_ADMINISTRACION(35L),
    SANCION_POR_INEXACTITUD(36L),
    LIQUIDACION_DE_CORRECCION_ARITMETICA_DE_DERECHOS_DE_EXPLOTACION(37L),
    LIQUIDACION_DE_CORRECCION_ARITMETICA_DE_GASTOS_DE_ADMINISTRACION(38L),
    SANCION_POR_LIQUIDACION_DE_CORRECCION_ARITMETICA(39L),
    LIQUIDACION_DE_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(40L),
    LIQUIDACION_DE_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(41L),
    SANCION_DE_MULTA_POR_OPERACION_ILEGAL_(42L),
    LIQUIDACION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(43L),
    LIQUIDACION_DE_AFORO_POR_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_OMISION(44L),
    SANCION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS(45L),
    LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DERECHOS_DE_EXPLOTACION(46L),
    LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_GASTOS_DE_ADMINISTRACION(47L),
    SANCION_POR_EJECUCION_ANTICIPADA_DEL_CONTRATO(48L),
    MULTA_POR_LA_OMISION_DE_OBLIGACION_DE_CONSTITUIR_RENOVAR_O_AMPLIAR_LA_GARANTIA_DE_CUMPLIMIENTO(49L),
    MULTA_POR_EL_TRASLADO_DE_INSTRUMENTOS_DE_JUEGO_SIN_AUTORIZACION_DE_COLJUEGOS(50L),
    LIQUIDACION_UNILATERAL_DE_CONTRATOS_DERECHOS_DE_EXPLOTACION(51L),
    LIQUIDACION_UNILATERAL_DE_CONTRATOS_GASTOS_DE_ADMINISTRACION(52L),
    LIQUIDACION_DE_MUTUO_ACUERDO_DE_CONTRATOS_DERECHOS_DE_EXPLOTACION(53L),
    LIQUIDACION_DE_MUTUO_ACUERDO_DE_CONTRATOS_GASTOS_DE_ADMINISTRACION(54L),
    SENTENCIAS_JUDICIALES_O_LAUDOS_ARBITRALES(55L),
    AUTO_APROBATORIO_DE_CONCILIACION(56L),
    ACUERDOS_DE_PAGO_DE_LA_LIQUIDACION_DE_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(57L),
    ACUERDOS_DE_PAGO_DE_LIQUIDACION_DE_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(58L),
    ACUERDOS_DE_PAGO_DE_SANCION_DE_MULTA_POR_OPERACION_ILEGAL(59L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_DE_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(60L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_DE_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(61L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_SANCION_DE_MULTA_POR_OPERACION_ILEGAL(62L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_DE_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(63L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_DE_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_POR_OPERACION_ILEGAL(64L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_SANCION_DE_MULTA_POR_OPERACION_ILEGAL(65L),
    ACUERDOS_DE_PAGO_SOBRE_LIQUIDACION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(66L),
    ACUERDOS_DE_PAGO_SOBRE_LIQUIDACION_DE_AFORO_POR_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_OMISION(67L),
    ACUERDOS_DE_PAGO_SOBRE_SANCION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(68L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(69L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_DE_AFORO_POR_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_OMISION(70L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_SANCION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS(71L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(72L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_DE_AFORO_POR_GASTOS_DE_ADMINISTRACION_NO_DECLARADOS_OMISION(73L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_SANCION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(74L),
    ACUERDOS_DE_PAGO_SOBRE_LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DE_DERECHOS_DE_EXPLOTACION(75L),
    ACUERDOS_DE_PAGO_SOBRE_LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DE_GASTOS_DE_ADMINISTRACION(76L),
    ACUERDOS_DE_PAGO_DE_SANCION_POR_INEXACTITUD(77L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DE_DERECHOS_DE_EXPLOTACION(78L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DE_GASTOS_DE_ADMINISTRACION(79L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_SANCION_POR_INEXACTITUD(80L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DE_DERECHOS_DE_EXPLOTACION(81L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_DE_REVISION_POR_PAGO_DE_MENOR_VALOR_DE_GASTOS_DE_ADMINISTRACION(82L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_SANCION_POR_INEXACTITUD(83L),
    ACUERDOS_DE_PAGO_LIQUIDACION_DE_CORRECCION_ARITMETICA_DE_DERECHOS_DE_EXPLOTACION(84L),
    ACUERDOS_DE_PAGO_LIQUIDACION_DE_CORRECCION_ARITMETICA_DE_GASTOS_DE_ADMINISTRACION(85L),
    ACUERDOS_DE_PAGO_SANCION_POR_LIQUIDACION_DE_CORRECCION_ARITMETICA(86L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_CORRECCION_ARITMETICA_DE_DERECHOS_DE_EXPLOTACION(87L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_LIQUIDACION_CORRECCION_ARITMETICA_DE_GASTOS_DE_ADMINISTRACION(88L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_SANCION_POR_LIQUIDACION_DE_CORRECCION_ARITMETICA(89L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_CORRECCION_ARITMETICA_DE_DERECHOS_DE_EXPLOTACION(90L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LIQUIDACION_CORRECCION_ARITMETICA_DE_GASTOS_DE_ADMINISTRACION(91L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_SANCION_POR_LIQUIDACION_DE_CORRECCION__ARITMETICA(92L),
    ACUERDOS_DE_PAGO_SANCION_POR_EJECUCION_ANTICIPADA_DEL_CONTRATO(93L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_SOBRE_LA_SANCION_POR_EJECUCION_ANTICIPADA(94L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_LA_SANCION_POR_EJECUCION_ANTICIPADA(95L),
    ACUERDOS_DE_PAGO_MULTAS_POR_INCUMPLIMIENTO_CONTRACTUAL(96L),
    ACUERDOS_DE_PAGO_INTERESES_FINANCIACION_SOBRE_MULTAS_POR_INCUMPLIMIENTO_CONTRACTUAL(97L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_SOBRE_MULTAS_POR_INCUMPLIMIENTO_CONTRACTUAL(98L),
    ACUERDOS_DE_PAGO_DE_MULTA_POR_LA_OMISION_DE_OBLIGACION_DE_CONSTITUIR_RENOVAR_O_AMPLIAR_LA_GARANTIA_DE_CUMPLIMIENTO(99L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_MULTA_POR_LA_OMISION_DE_OBLIGACION_DE_CONSTITUIR_RENOVAR_O_AMPLIAR_LA_GARANTIA_DE_CUMPLIMIENTO(100L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_MULTA_POR_LA_OMISION_DE_OBLIGACION_DE_CONSTITUIR_RENOVAR_O_AMPLIAR_LA_GARANTIA_DE_CUMPLIMIENTO(101L),
    ACUERDOS_DE_PAGO_DE_MULTA_POR_EL_TRASLADO_DE_INSTRUMENTOS_DE_JUEGO_SIN_AUTORIZACION_DE_COLJUEGOS(102L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_DE_MULTA_POR_EL_TRASLADO_DE_INSTRUMENTOS_DE_JUEGO_SIN_AUTORIZACION_DE_COLJUEGOS(103L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_DE_MULTA_POR_EL_TRASLADO_DE_INSTRUMENTOS_DE_JUEGO_SIN_AUTORIZACION_DE_COLJUEGOS(104L),
    ACUERDOS_DE_PAGO_LIQUIDACION_UNILATERAL_DE_CONTRATOS_DE(105L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_DE_LA_LIQUIDACION_UNILATERAL_DE_CONTRATOS_DE(106L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_DE_LA_LIQUIDACION_UNILATERAL_DE_CONTRATOS_DE(107L),
    ACUERDOS_DE_PAGO_LIQUIDACION_UNILATERAL_DE_CONTRATOS_GA(108L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_DE_LA_LIQUIDACION_UNILATERAL_DE_CONTRATOS_GA(109L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_DE_LA_LIQUIDACION_UNILATERAL_DE_CONTRATOS_GA(110L),
    ACUERDOS_DE_PAGO_LIQUIDACION_DE_MUTUO_ACUERDO_DE_CONTRATOS_DE(111L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_DE_LA_LIQUIDACION_POR_MUTUO_ACUERDO_DE_CONTRATOS_DE(112L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_DE_LA_LIQUIDACION_POR_MUTUO_ACUERDO_DE_CONTRATOS_DE(113L),
    ACUERDOS_DE_PAGO_LIQUIDACION_POR_MUTUO_ACUERDO_DE_CONTRATOS_GA(114L),
    ACUERDOS_DE_PAGO_INTERESES_DE_FINANCIACION_DE_LA_LIQUIDACION_POR_MUTUO_ACUERDO_DE_CONTRATOS_GA(115L),
    ACUERDOS_DE_PAGO_INTERESES_NO_FINANCIADOS_DE_LA_LIQUIDACION_POR_MUTUO_ACUERDO_DE_CONTRATOS_GA(116L),
    DERECHOS_DE_EXPLOTACION_PROMOCIONALES(117L),
    GASTOS_DE_ADMINISTRACION_PROMOCIONALES(118L),
    DERECHOS_DE_EXPLOTACION_RIFAS(119L),
    GASTOS_DE_ADMINISTRACION_RIFAS(120L),
    SANCION_DE_AFORO_POR_DERECHOS_DE_EXPLOTACION_NO_DECLARADOS_OMISION(121L);
    
    
    


    /** ID del Estado */
    private Long id;

    /**
     * Constructor.
     * @param id
     */
    EnumConceptoCuota(Long id) {
        this.id = id;
    }


    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }
}
