package co.gov.coljuegos.siicol.ejb.enumeration;


/**
 * Enumerado para el Estado del Proceso Sancionatorio de Ilegalidad.
 * - Obtenidos de la tabla <i>SII_ESTADO_PROC_SAN_ILEG</i>.
 */
public enum EnumEstadoProcSanIleg {
    BORRADOR_COMUNICACION_INICIO(1L),
    COMUNICACION_INICIO_FIRMADA(2L),
    RESULTADO_ENVIO_COMUNICACION_INICIO(3L),
    BORRADOR_AUTO_FORMULACION_CARGOS(4L),
    AUTO_FORMULACION_CARGOS_EN_NUMERACION(5L),
    BORRADOR_AUTO_DECRETA_PRUEBAS(6L),
    AUTO_DECRETA_PRUEBAS_EN_NUMERACION(7L),
    BORRADOR_AUTO_QUE_NIEGA_PRUEBAS_Y_CORRE_TRASLADO_ALEGATOS_(8L),
    AUTO_QUE_NIEGA_PRUEBAS_Y_CORRE_TRASLADO_ALEGATOS_EN_NUMERACION(9L),
    BORRADOR_AUTO_TRASLADO_ALEGATOS(10L),
    AUTO_TRASLADO_ALEGATOS_EN_NUMERACION(11L),
    TRAMITE_RESOLUCION_SIN_SANCION(12L),
    TRAMITE_RECURSO_REPOSICION(13L),
    TRAMITE_RECURSO_APELACION(14L),
    TERMINADO_SIN_SANCION(15L),
    TERMINADO_CON_SANCION(16L),
    BORRADOR_AUTO_ARCHIVO(17L),
    AUTO_ARCHIVO_EN_NUMERACION(18L),
    POR_DETERMINAR_SUJETO_SANCIONABLE(19L),
    ARCHIVADO(20L),
    AUTO_FORMULACION_CARGOS_NOTIFICADO(21L),
    AUTO_NIEGA_PRUEBAS_COMUNICADO(22L),
    AUTO_TRASLADO_ALEGATOS_COMUNICADO(23L),
    TRAMITE_AUTO_DECRETA_PRUEBAS(24L),
    TRAMITE_AUTO_FORMULACION_CARGOS(25L),
    TRAMITE_AUTO_NIEGA_PRUEBAS_Y_CORRE_TRASLADO_ALEGATOS(26L),
    TRAMITE_AUTO_TRASLADO_ALEGATOS(27L),
    TRAMITE_RESOLUCION_CON_SANCION(28L),
    AUTO_DECRETA_PRUEBAS_COMUNICADO(29L),
    AUTO_DECRETA_PRUEBAS_NUMERADO(30L),
    AUTO_NIEGA_PRUEBAS_NUMERADO(31L),
    AUTO_TRASLADO_ALEGATOS_NUMERADO(32L);
    
    
    
    private Long id;
    
    
    /**
     * Constructor.
     * @param id
     */
    EnumEstadoProcSanIleg(Long id) {
        this.id = id;
    }


    public Long getId() {
        return id;
    }
}
