/* 
 * SISTEMA	: SIICOL
 * AUTOR	: Camilo Miranda
 * FECHA	: 19-12-2013
 */

package co.gov.coljuegos.siicol.ejb.enumeration;


/**
 * Enumerado asociado a los tipos de Documento de ColJuegos.
 * Obtenidos de la tabla <i>SII_TIPO_DOCUMENTO_COLJUEGOS</i>.
 * @author Camilo Miranda
 */
public enum EnumTipoDocColjuegos {
    
    OFICIO_DE_ADJUDICACION(1L),
    OFICIO_DE_SOLICITUD(2L),
    OFICIO_DE_RESPUESTA_DEL_OPERADOR(3L),
    EVALUACION_JTF(4L),
    RESOLUCION_AUTORIZACION_LOCALIZADOS(5L),
    OFICIO_DE_DESIGNACION_DE_SUPERVISOR(6L),
    ACTA_INI_CONTRATO(7L),
    PROC_CONTRAT(8L),
    POLIZA_CONTRAT(9L),
    CIERRE_RECAUDO(10L),
    DISTRIBUCION_MES(11L),
    CONTRATO_CONCESION(12L),
    OFICIO_DESIGNACION_SUPERVISOR(13L),
    APROPIACION_INICIAL(21L),
    SOLICITUD_CDP(22L),
    CDP(23L),
    INCREMENTO_CDP(24L),
    DECREMENTO_CDP(25L),
    SOLICITUD_RP(26L),
    RP(27L),
    SOL_EST_MERCADO(28L),
    ESTUDIO_DE_MERCADO(29L),
    ESTUDIOS_PREVIOS(30L),
    INVITACION_PROCESO_SELECCION_DIRECTA_CERRADA(31L),
    ALCANCE_INVITACION_PROCESO_SELECCION_DIRECTA_CERRADA(32L),
    SOLICITUD_PAGO(33L),
    ORDEN_DE_PAGO(34L),
    INCREMENTO_RP(35L),
    DECREMENTO_RP(36L),
    ACTA_DE_RECEPCION_DE_PROPUESTA(41L),
    OTROSI_CONTRATO_CONCESION(42L),
    OBLIGACION(43L),
    OFICIO_LIQUIDACION(44L),
    SOLICITUD_AUTORIZA(45L),
    DOCUMENTO_CONTABLE(46L),
    SOLICITUD_PFC_MENSUAL(47L),
    TRASLADO_CUENTAS_BANCARIAS(48L),
    MODIFICACION_PRESUPUESTAL(49L),
    DOCUMENTO_CONPES(50L),
    BENEFICIARIO_ENTE(14L),
    USUARIO(51L),
    LIQUIDACION_CONTRATO_CONCESION(16L),
    RESOLUCION_LIQUIDACION_UNILATERAL(17L ),
    TRASLADO_ENTRE_ITEMS_DEL_PLAN_DE_CONTRATACION(18L),
    SUSPENSION_CONTRATO_CONCESION(52L),
    TIPO_DOCUMENTO_CONTABLE(20L),
    REPARTO_FISCALIZADOR(37L),
    ASIGNACION_RECAUDO(38L),
    AUTO_COMISORIO_ACC(40L),
    RESOLUCION_DESISTIMIENTO_LOCALIZADOS(53L),
    PROCESO_INCUMPLIMIENTO_CONTRACTUAL(54L),
    PROCESO_SANCIONATORIO_FISCALIZACION(55L),
    PROCESO_SANCIONATORIO_ILEGALIDAD(56L),
    INFORME_VERIFICACION_CAMPO(57L),
    CARGUE_LIQ_ACT_ADM(58L),
    REINTEGRO_PAGADURIA(59L),
    ACTA_DESTRUCCION(60L),
    AUTO_COMISORIO(61L),
    ORDEN_DE_TRABAJO(62L);
    
    private Long id;
    
    
    /**
     * Constructor.
     * @param id
     */
    private EnumTipoDocColjuegos(Long id) {
        this.id = id;
    }
    
    
    
    public Long getId() {
        return id;
    }
}
