package co.gov.coljuegos.siicol.ejb.enumeration;


/**
 * Enumerado para los Tipos de Apuesta.
 * - Obtenidos de la tabla <i>SII_TIPO_APUESTA</i>.
 * @author Camilo Miranda
 */
public enum EnumTipoApuesta 
{
    MAQUINAS_ELECTRONICAS_TRAGAMONEDAS_CON_APUESTA_HASTA_500(1L),
    MAQUINAS_ELECTRONICAS_TRAGAMONEDAS_CON_APUESTA_MAYOR_A_500(2L),
    MAQUINAS_ELECTRONICAS_TRAGAMONEDAS_CON_APUESTA_PROGRESIVA(3L),
    MESAS_DE_CASINO(4L),
    ESFERODROMOS(5L),
    SILLAS_DE_BINGO_CON_APUESTA_HASTA_250_PESOS(6L),
    SILLAS_DE_BINGO_CON_APUESTA_MAYOR_A_250(7L),
    SILLAS_DE_BINGO_CON_APUESTA_HASTA_250(8L),
    SILLAS_DE_BINGO_CON_APUESTA_MAYOR_A_250_HASTA_500(9L),
    SILLAS_DE_BINGO_CON_APUESTA_MAYOR_A_500(10L),
    SILLAS_DE_BINGO_SIMULTANEAS_INTERCONECTADAS_CON_APUESTA_HASTA_250(11L),
    SILLAS_DE_BINGO_SIMULTANEAS_INTERCONECTADAS_CON_APUESTA_MAYOR_A_250_HASTA_500(12L),
    SILLAS_DE_BINGO_SIMULTANEAS_INTERCONECTADAS_CON_APUESTA_MAYOR_A_500(13L),
    DEMAS_JUEGOS_LOCALIZADOS(14L),
    RIFAS_DE_CARACTER_NACIONAL(15L),
    EXCEPTUADOS_DE_CARACTER_NACIONAL(16L),
    CON_RESOLUCION_DE_CARACTER_NACIONAL(17L),
    BALOTO(18L),
    SUPER_ASTRO(19L),
    APUESTAS_EN_EVENTOS_DEPORTIVOS_GALLISTICOS_CANINOS_Y_SIMILARES(20L),
    REPORTE_DE_TRANSACCIONES_SUPERIORES_A_10_MILLONES_DE_PESOS(21L),
    PARA_MUNICIPIOS_MENORES_DE_100000_HABITANTES_CARTONES_HASTA_250_SILLAS_SIMULTANEAS(22L),
    PARA_MUNICIPIOS_MENORES_DE_100000_HABITANTES_CARTONES_DE_MAS_DE_250_SILLAS_SIMULTANEAS(23L),
    APUESTAS_Y_CARRERAS_DEPORTIVAS_VIRTUALES_ACDV(24L);
    
    
    
    private Long id;
    
    
    /**
     * Constructor.
     */
    EnumTipoApuesta(Long id) {
        this.id = id;
    }


    public Long getId() {
        return id;
    }
}
